name: CI_CACHE

on:
  workflow_dispatch:
  push:
    branches:
    - main2
  #schedule:
  #- cron: "*/5 * * * *"
jobs:
  puppeteer_cache:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2.5.0
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Puppeteer
        run: |
          npm install --save puppeteer request node-fetch
      - name: IP Address
        run: curl ipinfo.io/json
