name: CI_JSON

on:
  workflow_dispatch:
  push:
    branches:
    - main
  #schedule:
  #- cron: "*/5 * * * *"
jobs:
  prusa_like_1:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      - name: json
        run: |
          node json.js

