name: CI_JSON

on:
  workflow_dispatch:
  push:
    branches:
    - main2
  #schedule:
  #- cron: "*/5 * * * *"
jobs:
  prusa_like_1:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      - name: json
        run: |
          node json.js
      - name: Commit report
        continue-on-error: true
        run: |
          git config --global user.name 'MikeeI'
          git config --global user.email 'MikeeI@users.noreply.github.com'
          git commit -am "Automated report"
          git push

