name: CI_PUSH

on:
  push:
    branches:
    - main
  schedule:
   - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  prusa_download_5:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2.5.0
      - name: Install Puppeteer
        run: |
          npm install --save puppeteer request node-fetch
      - name: IP Address
        run: curl ipinfo.io/json
      - name: Download
        run: |
          sudo git clone https://github.com/P3TERX/warp.sh
          cd warp.sh
          sudo bash warp.sh install
          sudo bash warp.sh proxy
          sudo bash warp.sh status
          cd ..
          node push_5.js
