name: CI

on:
  push:
    branches:
    - main

jobs:
  puppeteer:
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
      - name: Install dependencies and run tests
        run: |
          npm install npx \
          #npx playwright install-deps chromium \
          npm install --save puppeteer request node-fetch --verbose
      - name: IP Address
        run: curl ipinfo.io/json
      - name: Download
        run: |
          node index.js 
